// Test DSL, app profile and plan (traceability) schemas.
// Tests are authored by humans or generated by `qa plan` from documents; both go through these schemas.
import { z } from 'zod';
import { PLATFORMS, platformsFor } from '../core/platform.ts';
import type { Platform } from '../core/types.ts';

const Intent = z.string().min(1).describe('What a human sees, e.g. "항공편 찾기 버튼" or "the search field". Never an implementation id.');

const TextMatch = z.union([
  z.string().min(1).describe('Plain string (NFC). In selectors: exact equality. In text assertions: substring.'),
  z.strictObject({ regex: z.string().min(1), flags: z.string().regex(/^[imsu]*$/).optional() }),
]);

const StateFilter = z.strictObject({
  enabled: z.boolean().optional(),
  checked: z.boolean().optional(),
  selected: z.boolean().optional(),
  focused: z.boolean().optional(),
});

/** Deterministic selector (text/desc/id) and/or semantic `intent`, optionally narrowed by element state. */
const Selector = z
  .strictObject({
    intent: Intent.optional(),
    text: TextMatch.optional(),
    desc: TextMatch.optional(),
    id: TextMatch.optional().describe('Android resource-id / iOS accessibilityIdentifier'),
    state: StateFilter.optional(),
  })
  .refine((s) => s.intent !== undefined || s.text !== undefined || s.desc !== undefined || s.id !== undefined, 'selector needs intent, text, desc or id');

const Target = z.union([Intent, Selector]);

const NormPoint = z.strictObject({
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
});

/** Postcondition checked after the step's action settles. */
const Expectation = z.union([
  z.strictObject({ see: Target }),
  z.strictObject({ text: TextMatch }),
  z.strictObject({ noText: TextMatch }),
  z.strictObject({ claim: z.string().min(1) }),
]);

/** Loop/branch condition: deterministic text checks or a resolved target. */
const Condition = z.union([z.strictObject({ see: Target }), z.strictObject({ text: TextMatch }), z.strictObject({ noText: TextMatch })]);

const Common = {
  timeout: z.number().int().positive().max(120_000).optional().describe('ms for this step, counted from the last mutating action'),
  optional: z.boolean().optional().describe('Failure is recorded as SKIPPED instead of failing the test'),
  platforms: z.array(z.enum(PLATFORMS)).min(1).optional().describe('Run this step only on these platforms'),
  expect: z.union([Expectation, z.array(Expectation).min(1)]).optional(),
  expectNoChange: z.boolean().optional().describe('Allow a mutation step to leave the screen unchanged'),
  allowRisky: z.boolean().optional().describe('Required to act on destructive or unlabeled targets'),
  within: Intent.optional().describe('Restrict targets to inside this container'),
  nth: z.number().int().min(1).optional().describe('Pick the n-th match (reading order) among equal matches'),
  near: Intent.optional().describe('Prefer the match closest to this element'),
  note: z.string().optional(),
};
const CommonFields = z.strictObject(Common);
type CommonSpec = z.infer<typeof CommonFields>;

const Permission = z.enum(['allow', 'deny', 'unset']);

/** A JSONLogic rule is exactly one operator; `{}` or several operators would evaluate to a truthy object, not a condition. */
const JsonLogicRule = z
  .record(z.string(), z.unknown())
  .refine((r) => Object.keys(r).length === 1, 'rule must be a single JSONLogic operator')
  .describe('JSONLogic rule over the named groups; numbers are parsed from digit groups');

/** Every step kind except the recursive ones (`which`, `repeat`). */
const LeafStep = z.union([
  z.strictObject({
    launch: z.union([
      z.literal(true),
      z.strictObject({
        reset: z.enum(['none', 'relaunch', 'clear', 'reinstall']).optional().describe('clear on iOS also resets the simulator keychain (device-wide)'),
        permissions: z.record(z.string(), Permission).optional().describe('e.g. {location: allow, notifications: deny, camera: unset}'),
        arguments: z.array(z.string()).optional(),
      }),
    ]),
    ...Common,
  }),
  z.strictObject({ open: z.string().min(1).describe('Deep link / URL opened in the app under test'), ...Common }),
  z.strictObject({ tap: Target, ...Common }),
  z.strictObject({ longPress: Target, holdMs: z.number().int().min(300).max(10_000).default(1000), ...Common }),
  z.strictObject({ tapAt: NormPoint, ...Common }),
  z.strictObject({
    type: z.string(),
    into: Target,
    secure: z.boolean().optional(),
    append: z.boolean().optional().describe('Keep existing text instead of clearing first'),
    submit: z.boolean().optional().describe('Press the keyboard return/enter key after typing'),
    ...Common,
  }),
  z.strictObject({ clear: Target, ...Common }),
  z.strictObject({ press: z.enum(['enter', 'back', 'tab', 'escape', 'delete']), ...Common }),
  z.strictObject({ hideKeyboard: z.literal(true), ...Common }),
  z.strictObject({ see: Target, ...Common }),
  z.strictObject({ seeNot: Intent, ...Common }),
  z.strictObject({ assertText: TextMatch, ...Common }),
  z.strictObject({ assertNoText: TextMatch, ...Common }),
  z.strictObject({
    checkEach: z.strictObject({
      pattern: z.string().min(1).describe('JS regex with named groups, applied to every visible text line'),
      rule: JsonLogicRule,
      min: z.number().int().min(0).default(1).describe('Minimum number of matching lines'),
    }),
    ...Common,
  }),
  z.strictObject({ claim: z.string().min(1).describe('A factual statement about the current screen, judged by Jev (Noul)'), ...Common }),
  z.strictObject({
    remember: z.strictObject({
      name: z.string().regex(/^[A-Za-z_]\w*$/),
      from: z.union([Target, z.strictObject({ regex: z.string().min(1).describe('Applied to visible texts; group `value` or group 1 is stored') })]),
    }),
    ...Common,
  }),
  z.strictObject({ use: z.string().min(1).describe('Path to a *.flow.yaml subflow, relative to this file'), with: z.record(z.string(), z.string()).optional(), ...Common }),
  z.strictObject({
    scroll: z.strictObject({
      direction: z.enum(['up', 'down', 'left', 'right']),
      until: z.union([Target, z.strictObject({ text: TextMatch })]).optional(),
      max: z.number().int().min(1).max(30).default(5),
    }),
    ...Common,
  }),
  z.strictObject({ swipe: z.strictObject({ from: NormPoint, to: NormPoint, durationMs: z.number().int().min(50).max(5000).default(450) }), ...Common }),
  z.strictObject({ back: z.literal(true), ...Common }),
  z.strictObject({ location: z.strictObject({ lat: z.number().min(-90).max(90), lon: z.number().min(-180).max(180) }), ...Common }),
  z.strictObject({ wait: z.union([z.number().int().positive().max(60_000), z.strictObject({ until: z.union([Target, z.strictObject({ text: TextMatch })]) })]), ...Common }),
  z.strictObject({ capture: z.string().min(1), ...Common }),
]);

export interface WhichStepSpec extends CommonSpec {
  which: Record<string, StepSpec[]>;
}
export interface RepeatStepSpec extends CommonSpec {
  repeat: { times?: number; while?: z.infer<typeof Condition>; steps: StepSpec[] };
}
export type StepSpec = z.infer<typeof LeafStep> | WhichStepSpec | RepeatStepSpec;

const WhichStep = z.strictObject({
  which: z.record(Intent, z.array(z.lazy(() => Step))).refine((o) => Object.keys(o).length >= 2, 'which needs ≥2 branches'),
  ...Common,
});
const RepeatStep = z.strictObject({
  repeat: z
    .strictObject({
      times: z.number().int().min(1).max(10).optional(),
      while: Condition.optional(),
      steps: z.array(z.lazy(() => Step)).min(1),
    })
    .refine((r) => r.times !== undefined || r.while !== undefined, 'repeat needs times or while (max 10 iterations)'),
  ...Common,
});

const Step: z.ZodType<StepSpec> = z.union([LeafStep, WhichStep, RepeatStep]);

/** Every step kind; a step's kind is its one key from this list. Single source for loaders, runner, planner and server. */
export const STEP_KINDS = [
  'launch', 'open', 'tap', 'longPress', 'tapAt', 'type', 'clear', 'press', 'hideKeyboard', 'see', 'seeNot', 'assertText', 'assertNoText',
  'checkEach', 'claim', 'remember', 'which', 'repeat', 'use', 'scroll', 'swipe', 'back', 'location', 'wait', 'capture',
] as const;
export type StepKind = (typeof STEP_KINDS)[number];

/** The union member that validates each kind (used for per-kind error messages). Fails at load if the kind list drifts. */
export const STEP_BRANCHES: Record<StepKind, z.ZodType> = (() => {
  const byKey = new Map<string, z.ZodType>([...LeafStep.options, WhichStep, RepeatStep].map((option) => [Object.keys(option.shape)[0]!, option]));
  const missing = STEP_KINDS.filter((kind) => !byKey.has(kind));
  if (missing.length > 0 || byKey.size !== STEP_KINDS.length) throw new Error(`STEP_KINDS and the Step union disagree: ${[...byKey.keys()].join(', ')}`);
  return Object.fromEntries(STEP_KINDS.map((kind) => [kind, byKey.get(kind)!])) as Record<StepKind, z.ZodType>;
})();

/** Korean kind labels shared by the runner, reports, planner and server. */
export const STEP_KIND_LABEL: Record<StepKind, string> = {
  launch: '앱 실행',
  open: '링크 열기',
  tap: '탭',
  longPress: '길게 누르기',
  tapAt: '좌표 탭',
  type: '입력',
  clear: '지우기',
  press: '키 누르기',
  hideKeyboard: '키보드 숨기기',
  see: '보임',
  seeNot: '안 보임',
  assertText: '텍스트 확인',
  assertNoText: '텍스트 없음',
  checkEach: '각 줄 검사',
  claim: '판정',
  remember: '기억',
  which: '분기',
  repeat: '반복',
  use: '하위 흐름',
  scroll: '스크롤',
  swipe: '스와이프',
  back: '뒤로',
  location: '위치 설정',
  wait: '대기',
  capture: '캡처',
};

const KIND_SET: ReadonlySet<string> = new Set(STEP_KINDS);

/** The kind of a (possibly unvalidated) step object, or null when it has none of the known kind keys. */
export function findStepKind(step: object): StepKind | null {
  for (const key of Object.keys(step)) if (KIND_SET.has(key)) return key as StepKind;
  return null;
}

export function stepKind(step: StepSpec): StepKind {
  const kind = findStepKind(step);
  if (kind === null) throw new Error(`알 수 없는 스텝: ${JSON.stringify(step)}`);
  return kind;
}

function describe(value: unknown): string {
  if (value === true || value === undefined) return '';
  if (typeof value === 'string' || typeof value === 'number') return String(value);
  if (value && typeof value === 'object') {
    if ('regex' in value) return `/${String(value.regex)}/`;
    return Object.entries(value)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `${k}=${typeof v === 'string' || typeof v === 'number' ? v : describe(v) || JSON.stringify(v)}`)
      .join(', ');
  }
  return JSON.stringify(value);
}

/**
 * "탭: 출국장", "입력(2자) → 검색창", "반복: 3회" … — the one step label used by run events, reports and the server's
 * plan view. Labels are built before the step runs, before the target is observed, so a `type` label never carries the
 * typed text (the field may turn out to be secure): only its length, or `변수` when the text has a `${…}` placeholder;
 * a `which`/`repeat` label never carries its nested steps. The evidence sanitizer masks profile `redact` matches and
 * known secrets in the rest.
 */
export function stepLabel(step: StepSpec): string {
  const kind = stepKind(step);
  if ('type' in step) return `${STEP_KIND_LABEL[kind]}(${step.type.includes('${') ? '변수' : `${[...step.type].length}자`}) → ${describe(step.into)}`;
  let detail: string;
  if ('which' in step) detail = Object.keys(step.which).join(' | ');
  else if ('repeat' in step) detail = step.repeat.times !== undefined ? `${step.repeat.times}회` : `조건 ${describe(step.repeat.while)}`;
  else if ('wait' in step) detail = typeof step.wait === 'number' ? `${step.wait}ms` : `${describe(step.wait.until)}까지`;
  else if ('checkEach' in step) detail = `/${step.checkEach.pattern}/`;
  else if ('remember' in step) detail = `${step.remember.name} ← ${describe(step.remember.from)}`;
  else if ('scroll' in step) detail = `${step.scroll.direction}${step.scroll.until ? ` → ${describe(step.scroll.until)}` : ''}`;
  else detail = describe(Object.entries(step).find(([key]) => key === kind)?.[1]);
  return detail ? `${STEP_KIND_LABEL[kind]}: ${detail}` : STEP_KIND_LABEL[kind];
}

const Interrupt = z.strictObject({
  see: Target,
  do: z.array(Step).min(1),
  max: z.number().int().min(1).max(10).default(3),
});

/** Reusable subflow file (`*.flow.yaml`) referenced by `use:`. `${name}` placeholders are filled from `with`. */
export const FlowSpec = z.strictObject({
  name: z.string().min(1),
  steps: z.array(Step).min(1),
});
export type FlowSpec = z.infer<typeof FlowSpec>;

export const TestSpec = z.strictObject({
  id: z.string().regex(/^[\w.-]+$/).optional(),
  name: z.string().min(1),
  app: z.string().min(1).describe('App profile id (apps/<id>.yaml)'),
  platforms: z.array(z.enum(PLATFORMS)).min(1).optional(),
  tags: z.array(z.string()).optional(),
  covers: z.array(z.string()).optional().describe('Requirement ids this test verifies (traceability)'),
  source: z
    .strictObject({
      plan: z.string().describe('Path to plan.json that produced this test'),
      status: z.enum(['draft', 'approved', 'rejected']),
    })
    .optional(),
  start: z.enum(['launch', 'attach']).default('launch'),
  reset: z.enum(['none', 'relaunch', 'clear', 'reinstall']).default('relaunch'),
  budget: z
    .strictObject({
      steps: z.number().int().positive().default(80),
      seconds: z.number().int().positive().default(600),
      jevCalls: z.number().int().positive().default(120),
    })
    .optional(),
  when: z.array(Interrupt).optional(),
  setup: z.array(Step).optional().describe('Runs before steps; failure fails the test'),
  steps: z.array(Step).min(1),
  teardown: z.array(Step).optional().describe('Always runs after steps; failures are reported as warnings and never change the verdict'),
});
export type TestSpec = z.infer<typeof TestSpec>;

/** App ids reach device shells and backup paths, so only real package/bundle id shapes are accepted. */
const AndroidPackage = z.string().regex(/^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z][A-Za-z0-9_]*)+$/, 'Android package id (e.g. kr.tteonam.app)');
const IosBundleId = z.string().regex(/^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$/, 'iOS bundle id (e.g. kr.tteonam.app)');

/** Absolute http(s) URL without credentials — it is opened in a browser and printed in evidence. */
const WebUrl = z.url({ protocol: /^https?$/, hostname: z.regexes.hostname }).refine((u) => {
  const url = new URL(u);
  return url.username === '' && url.password === '';
}, 'URL must not contain credentials');

/** `scheme://host[:port]` exactly as `URL.origin` prints it. */
const WebOrigin = z.string().refine((o) => {
  try {
    const url = new URL(o);
    return (url.protocol === 'http:' || url.protocol === 'https:') && url.origin === o;
  } catch {
    return false;
  }
}, 'origin must be scheme://host[:port] (e.g. https://example.com)');

export const AppProfile = z
  .strictObject({
    id: z.string().regex(/^[\w.-]+$/),
    name: z.string().min(1),
    build: z.enum(['dev', 'release']).default('release').describe('dev builds may show RN LogBox warnings (WARN) — errors are FAIL either way'),
    android: z
      .strictObject({
        package: AndroidPackage,
        activity: z.string().optional(),
        apk: z.string().optional(),
      })
      .optional(),
    ios: z
      .strictObject({
        bundleId: IosBundleId,
        app: z.string().optional().describe('Simulator .app path for install/reinstall'),
      })
      .optional(),
    web: z
      .strictObject({
        url: WebUrl.describe('Start URL opened by `launch` on every platform'),
        origins: z.array(WebOrigin).min(1).optional().describe('Allowed origins; default = the start URL origin'),
        viewport: z
          .strictObject({ width: z.number().int().min(320).max(3840), height: z.number().int().min(320).max(2160) })
          .default({ width: 1280, height: 800 })
          .describe('Desktop browser viewport in CSS px'),
        platforms: z.array(z.enum(PLATFORMS)).min(1).optional().describe('Platforms this site is tested on; default = all'),
      })
      .optional()
      .describe('Website profile: runs in Chrome/Safari on desktop, Android and iOS. Mutually exclusive with android/ios.'),
    risk: z
      .strictObject({
        deny: z.array(z.string()).default([]).describe('Extra destructive keywords for this app'),
        allow: z.array(z.string()).default([]).describe('Exact labels that are known safe despite matching a keyword'),
      })
      .optional(),
    redact: z.array(z.string()).default([]).describe('Regexes whose matches are masked before any text leaves the machine'),
    volatile: z.array(z.string()).default([]).describe('Regexes for texts ignored by screen fingerprints (clocks, timestamps)'),
    docs: z.array(z.string()).default([]).describe('Default document sources for `qa plan`'),
  })
  .refine((p) => (p.web ? !p.android && !p.ios : Boolean(p.android || p.ios)), {
    message: 'profile needs android/ios (app) or web (website), not both',
  });
export type AppProfile = z.infer<typeof AppProfile>;

/** Platforms a profile runs on, in display order: a web profile's declared (or every web) platform; an app profile's configured ones. */
export function profilePlatforms(profile: Pick<AppProfile, 'android' | 'ios' | 'web'>): Platform[] {
  const web = profile.web;
  if (web) return web.platforms ? PLATFORMS.filter((p) => web.platforms!.includes(p)) : platformsFor('web');
  return PLATFORMS.filter((p) => (p === 'android' && profile.android) || (p === 'ios' && profile.ios));
}

// ───────────────────────── plan / traceability ─────────────────────────

export const Requirement = z.strictObject({
  /** Stable id: <doc-slug>#<heading-slug>[.<n>] */
  id: z.string().min(1),
  doc: z.string(),
  /** Heading path, e.g. ["떠남", "터미널과 출국장", "혼잡 단계"]. */
  section: z.array(z.string()),
  lines: z.tuple([z.number().int(), z.number().int()]).nullable(),
  text: z.string().min(1),
  /** sha256 of text; used to detect stale tests when documents change. */
  digest: z.string(),
});
export type Requirement = z.infer<typeof Requirement>;

export const PlanFile = z.strictObject({
  version: z.literal(1),
  app: z.string(),
  createdAt: z.string(),
  llm: z.strictObject({ provider: z.string(), model: z.string().nullable() }),
  docs: z.array(z.strictObject({ path: z.string(), sha256: z.string(), kind: z.string() })),
  requirements: z.array(Requirement),
  tests: z.array(
    z.strictObject({
      file: z.string(),
      covers: z.array(z.string()),
      status: z.enum(['draft', 'approved', 'rejected']),
      review: z.strictObject({
        addressesRequirement: z.number().nullable(),
        unrelatedSteps: z.number().nullable(),
        needsClarification: z.number().nullable(),
        issues: z.array(z.string()),
      }),
    }),
  ),
  untestable: z.array(z.strictObject({ requirement: z.string(), reason: z.string() })),
});
export type PlanFile = z.infer<typeof PlanFile>;

// ───────────────────────── checkEach rules ─────────────────────────
// The static rule language (invariant 1), shared by plan validation and the runner; `src/runner/rule.ts` evaluates a
// rule only after `ruleProblem` accepted it: every object in it is exactly one known operator with the operands it
// needs, every `var` outside a collection's logic names a group of the pattern (inside, it reads the current item), and
// at least one group is read. json-logic-js treats `{}` or a multi-key object as a truthy data literal and compares a
// missing operand as `undefined` (`{"==":[]}` is true), so an unchecked rule could PASS without testing anything.

/**
 * json-logic-js 2.0.5 operators a rule may use, each with the operand count [min, max] it needs to compute anything: the
 * library reads a missing operand as `undefined` (`{"%":[n]}` is NaN, and `NaN != 0` is true) and ignores extra ones.
 * The allow list is this table, so no allowed operator goes unchecked. `log` is left out: it prints group values to
 * stdout, around the evidence sanitizer. `missing` and `missing_some` are left out: they read groups by name without a
 * `var`, so a line lacking such a group would be evaluated (as "missing") instead of reported unobserved.
 */
const RULE_OPERATORS: Record<string, readonly [number, number]> = {
  '==': [2, 2],
  '===': [2, 2],
  '!=': [2, 2],
  '!==': [2, 2],
  '>': [2, 2],
  '>=': [2, 2],
  // A third operand makes a between check.
  '<': [2, 3],
  '<=': [2, 3],
  '!!': [1, 1],
  '!': [1, 1],
  '%': [2, 2],
  in: [2, 2],
  cat: [1, Infinity],
  // source, start, optional length.
  substr: [2, 3],
  '+': [2, Infinity],
  '*': [2, Infinity],
  // One operand negates.
  '-': [1, 2],
  '/': [2, 2],
  min: [1, Infinity],
  max: [1, Infinity],
  merge: [1, Infinity],
  // No default: a missing group must not turn into a value the rule accepts.
  var: [1, 1],
  // condition, then, else; each further condition-then pair goes before the else, so the count is odd (checked in
  // `operatorProblem`): without an else json-logic-js answers null when no condition holds (`!` makes that true).
  if: [3, Infinity],
  '?:': [3, 3],
  and: [1, Infinity],
  or: [1, Infinity],
  // array, logic applied to each item.
  filter: [2, 2],
  map: [2, 2],
  // array, logic, initial value: without one json-logic-js starts the accumulator at null, which the logic reads as a
  // value (`max` of -3 and null is 0).
  reduce: [3, 3],
  all: [2, 2],
  none: [2, 2],
  some: [2, 2],
};

/**
 * Operators whose operand at this index must be a list when evaluated, and whether a string counts: json-logic-js reads
 * any other value as an empty collection (`all`/`some`/`none` then answer without evaluating their logic, `filter`/`map`
 * give `[]`, `reduce` its initial value) and `in` of a non-list as false. `merge` takes any values (a non-list is one
 * item), so it needs no check. The runner checks these operands as it evaluates.
 */
export const RULE_LIST_OPERAND: Record<string, { at: number; strings: boolean }> = {
  all: { at: 0, strings: false },
  none: { at: 0, strings: false },
  some: { at: 0, strings: false },
  filter: { at: 0, strings: false },
  map: { at: 0, strings: false },
  reduce: { at: 0, strings: false },
  in: { at: 1, strings: true },
};

/**
 * Operators that evaluate the logic operand at this index once per item of their list, with that item as the data
 * (`reduce`: `{current, accumulator}`). A `var` there reads the item, never a group: json-logic-js reads a part the item
 * lacks as null, which a comparison can still call true (`{"none":[{"merge":[{"var":"n"}]},{">":[{"var":"n"},0]}]}`
 * reads `n` of the number 5 as null, not above 0, so no item fails).
 */
export const RULE_ITEM_LOGIC: Record<string, number> = { all: 1, none: 1, some: 1, filter: 1, map: 1, reduce: 1 };

/** `item`: inside a collection's logic (`RULE_ITEM_LOGIC`), where the data is the current item. */
function operandProblem(value: unknown, groups: ReadonlySet<string>, read: Set<string>, item: boolean, path: string): string | null {
  if (Array.isArray(value)) {
    for (const [i, entry] of value.entries()) {
      const problem = operandProblem(entry, groups, read, item, `${path}[${i}]`);
      if (problem) return problem;
    }
    return null;
  }
  return value !== null && typeof value === 'object' ? operatorProblem(value, groups, read, item, path) : null;
}

function operatorProblem(rule: unknown, groups: ReadonlySet<string>, read: Set<string>, item: boolean, path: string): string | null {
  if (rule === null || typeof rule !== 'object' || Array.isArray(rule)) return `${path}: JSONLogic 연산자 객체가 아님`;
  const entries = Object.entries(rule);
  if (entries.length !== 1) return `${path}: 연산자 객체는 키가 정확히 1개여야 함 (${entries.length}개: ${entries.map(([k]) => k).join(', ') || '없음'})`;
  const [op, operand] = entries[0]!;
  if (!Object.hasOwn(RULE_OPERATORS, op)) return `${path}: 알 수 없는 JSONLogic 연산자 "${op}"`;
  // json-logic-js passes a non-array operand as the single operand.
  const operands: unknown[] = Array.isArray(operand) ? operand : [operand];
  // Inside a collection's logic `{"var": []}` reads the item itself, like `{"var": ""}`.
  const [min, max] = item && op === 'var' ? ([0, 1] as const) : RULE_OPERATORS[op]!;
  // `if` needs an else after its condition-then pairs.
  const odd = op === 'if';
  if (operands.length < min || operands.length > max || (odd && operands.length % 2 === 0)) {
    const need = (min === max ? `${min}개` : max === Infinity ? `${min}개 이상` : `${min}~${max}개`) + (odd ? '의 홀수' : '');
    return `${path}.${op}: 피연산자 ${operands.length}개 (필요: ${need})`;
  }
  if (op === 'var') {
    const name = operands[0] ?? '';
    if (item) {
      if (typeof name !== 'string') return `${path}.var: 컬렉션 항목의 경로(문자열)여야 함`;
      // The data there is the item: a group name would read the item, not the group.
      return groups.has(name.split('.', 1)[0]!) ? `${path}.var: 컬렉션 안의 "${name}"는 이름 그룹이 아니라 현재 항목을 읽음 — 이름 그룹은 컬렉션 밖에서 읽으세요` : null;
    }
    if (typeof name !== 'string' || !name) return `${path}.var: pattern의 이름 그룹 이름(비어 있지 않은 문자열)이어야 함`;
    if (!groups.has(name)) return `${path}.var: "${name}"는 pattern의 이름 그룹이 아님`;
    read.add(name);
    return null;
  }
  if (!Array.isArray(operand)) return operandProblem(operand, groups, read, item, `${path}.${op}`);
  const logicAt = Object.hasOwn(RULE_ITEM_LOGIC, op) ? RULE_ITEM_LOGIC[op] : undefined;
  for (const [i, value] of operand.entries()) {
    const problem = operandProblem(value, groups, read, item || i === logicAt, `${path}.${op}[${i}]`);
    if (problem) return problem;
  }
  return null;
}

/**
 * Every named group of a `checkEach` pattern, compiled as the runner compiles it (`u`): an always-matching empty
 * alternative lists them all in `groups`. Throws on an invalid pattern.
 */
export function patternGroups(pattern: string): Set<string> {
  return new Set(Object.keys(new RegExp(`(?:${pattern})|`, 'u').exec('')!.groups ?? {}));
}

/**
 * Why `rule` is not a checkable JSONLogic rule over the pattern's named `groups` (Korean), or null. Every object in it
 * must be one known operator with the operands it needs, every `var` outside a collection's logic must name a group and
 * none inside may (it reads the item there), and the rule must read at least one group.
 */
export function ruleProblem(rule: unknown, groups: ReadonlySet<string>): string | null {
  const read = new Set<string>();
  const problem = operatorProblem(rule, groups, read, false, 'rule');
  if (problem) return problem;
  return read.size ? null : 'rule: var가 없어 아무 값도 검사하지 않음';
}

export { Step, Target, Selector, TextMatch, StateFilter, Condition, Expectation, Interrupt, NormPoint, AndroidPackage, IosBundleId };
